
name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: jaywcjlove/reference  # 例如: google/googletest
          upstream_branch: main                  # 原仓库的主分支名
          target_branch: main                    # 你仓库的主分支名
